# Generated by Django 3.2.25 on 2025-05-06 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0016_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
