# Generated by Django 3.2.25 on 2025-05-22 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0018_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('razorpay_order_id', models.CharField(max_length=200, null=True)),
                ('razorpay_payment_id', models.CharField(max_length=200, null=True)),
                ('razorpay_signature', models.CharField(max_length=200, null=True)),
                ('Paid', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Store.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Store.customer')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
