# Generated by Django 3.2.25 on 2025-07-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0021_accessories_electronics_home_appliances_mobiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessories',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='electronics',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='home_appliances',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mobiles',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
