# Generated by Django 3.2.25 on 2025-07-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0022_auto_20250705_1638'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accessories',
        ),
        migrations.DeleteModel(
            name='Electronics',
        ),
        migrations.DeleteModel(
            name='Home_Appliances',
        ),
        migrations.DeleteModel(
            name='Mobiles',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Digital',
            new_name='digital',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('mobiles', 'Mobiles'), ('accessories', 'Accessories'), ('home_appliances', 'Home Appliances')], default='mobiles', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
