# Generated by Django 3.2.25 on 2025-07-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0023_auto_20250706_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('mobiles', 'Mobiles'), ('accessories', 'Accessories'), ('home_appliances', 'Home Appliances'), ('products', 'products')], default='products', max_length=50),
        ),
    ]
